# -*- coding: utf-8 -*-
"""Copia de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXk-1qHzjENqBtCNXDdv8Q1Q-MluOiFN
"""

!pip install biopython
import streamlit as st
from Bio.SeqUtils import seq3, seq1
from Bio.Seq import Seq

# Configuración de la página
st.set_page_config(page_title="Predicción de Estructuras Secundarias", layout="wide")

# Título de la aplicación
st.header("Predicción de Estructuras Secundarias de Proteínas")

# Subir secuencia de proteínas
sequence_input = st.text_area("Introduce la secuencia de aminoácidos (en forma de una letra):", height=200)

if sequence_input:
    try:
        # Validar y limpiar secuencia
        protein_sequence = Seq(sequence_input.strip().upper())
        if not all(residue in "ACDEFGHIKLMNPQRSTVWY" for residue in protein_sequence):
            st.error("La secuencia contiene caracteres no validos. Usa el formato de una letra para aminoácidos.")
        else:
            # Mostrar información básica
            st.subheader("Información Básica:")
            st.write(f"Longitud de la secuencia: {len(protein_sequence)}aminoácidos")
            st.write(f"Secuencia en formato de tres letras: {seq3(protein_sequence)}")

            # Predicción simple (basada en patrones)
            st.subheader("Predicción de Estructura Secundaria (Simple):")
            alpha_helix = sum(protein_sequence.count(res) for res in "AEHKLMQ")
            beta_sheet = sum(protein_sequence.count(res) for res in "FWYVITC")
            coil = len(protein_sequence) - (alpha_helix + beta_sheet)

            st.write(f"Residuo favorable para hélices α: {alpha_helix}")
            st.write(f"Residuo favorable para láminas β: {beta_sheet}")
            st.write(f"Residuo en conformación coil: {coil}")

            # Graficar distribución
            st.subheader("Distribución de Estructuras Secundarias:")
            st.bar_chart({"Hélices α": alpha_helix, "Láminas β": beta_sheet, "Coil": coil})

            # Posibilidad de predicción avanzada
            st.info("Para predicciones avanzadas (PSIPRED, AlphaFold, etc.), se requiere integración con herramientas externas.")
    except Exception as e:
        st.error(f"Hubo un error procesando la secuencia: {e}")
else:
    st.info("Introduce una secuencia de aminoácidos para comenzar.")